{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "03ad0668-c5d8-476f-b1cf-19c3302140d8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# === Paths ===\n",
    "dataset_dir: \"data/your_dataset\"        # root folder with class subfolders\n",
    "encodings_dir: \"encodings1\"             # where encoded features will be written\n",
    "results_dir: \"results\"                  # where SVM metrics & models will be saved\n",
    "\n",
    "# === Runtime ===\n",
    "batch_size: 32\n",
    "num_workers: 2\n",
    "random_state: 42\n",
    "save_final_models: true                 # save {model}_svm.joblib and _classes.npy\n",
    "\n",
    "# === Models (exact names; alexnet is the only torchvision model) ===\n",
    "models:\n",
    "  - convnext_xxlarge\n",
    "  - resnetv2_152\n",
    "  - regnet_y_32gf\n",
    "  - convnext_xlarge\n",
    "  - densenet161\n",
    "  - densenet169\n",
    "  - densenet201\n",
    "  - convnextv2_tiny\n",
    "  - dpn131\n",
    "  - resnet152\n",
    "  - inception_next_tiny\n",
    "  - convnextv2_nano\n",
    "  - inception_next_small\n",
    "  - convnext_base\n",
    "  - dpn98\n",
    "  - inception_next_base\n",
    "  - dpn107\n",
    "  - mnasnet0_75\n",
    "  - convnext_large\n",
    "  - mnasnet1_0\n",
    "  - regnet_x_3_2gf\n",
    "  - efficientnet_b2\n",
    "  - convnext_small\n",
    "  - efficientnet_b0\n",
    "  - efficientnet_b1\n",
    "  - dpn68\n",
    "  - alexnet\n",
    "  - regnet_x_800mf\n",
    "  - efficientnet_b3\n",
    "  - efficientnet_b4\n",
    "  - convnext_tiny\n",
    "  - cs3darknet_x\n",
    "  - efficientnet_v2_s\n",
    "  - regnet_x_1_6gf\n",
    "  - mobilenet_v3_large\n",
    "  - vgg16_bn\n",
    "  - shufflenet_v2_x1_0\n",
    "  - shufflenet_v2_x2_0\n",
    "  - mnasnet1_3\n",
    "  - dpn92\n",
    "  - mobilenetv4_conv_small\n",
    "  - densenet121\n",
    "  - mobilenet_v3_small\n",
    "  - mnasnet0_5\n",
    "  - efficientnet_b5\n",
    "  - efficientnet_b7\n",
    "  - shufflenet_v2_x0_5\n",
    "  - regnet_x_400mf\n",
    "  - dpn68b\n",
    "  - vgg11_bn\n",
    "  - vgg13_bn\n",
    "  - mobilenet_v2\n",
    "  - vgg11\n",
    "  - regnet_y_16gf\n",
    "  - shufflenet_v2_x1_5\n",
    "  - convnextv2_pico\n",
    "  - densenetblur121d\n",
    "  - resnet34\n",
    "  - resnetv2_50\n",
    "  - regnet_y_8gf\n",
    "  - resnet18\n",
    "  - cs3darknet_focus_l\n",
    "  - convnext_pico\n",
    "  - cs3darknet_focus_m\n",
    "  - inception_v3\n",
    "  - regnet_y_800mf\n",
    "  - vgg13\n",
    "  - convnext_nano\n",
    "  - vgg16\n",
    "  - resnet50\n",
    "  - regnet_y_400mf\n",
    "  - convnextv2_huge\n",
    "  - efficientnet_b6\n",
    "  - vgg19_bn\n",
    "  - googlenet\n",
    "  - resnetv2_101\n",
    "  - efficientnet_v2_m\n",
    "  - convnextv2_base\n",
    "  - convnextv2_large\n",
    "  - regnet_y_3_2gf\n",
    "  - vgg19\n",
    "  - resnet101\n",
    "  - wide_resnet101_2\n",
    "  - regnet_y_1_6gf\n",
    "  - xception65\n",
    "  - resnext101_32x8d\n",
    "  - resnext50_32x4d\n",
    "  - regnet_x_32gf\n",
    "  - convnextv2_atto\n",
    "  - wide_resnet50_2\n",
    "  - regnet_x_16gf\n",
    "  - convnextv2_femto\n",
    "  - regnet_x_8gf\n",
    "  - inception_v4\n",
    "  - mobilenetv4_conv_medium\n",
    "  - mobilenetv4_conv_large\n",
    "  - efficientnet_v2_l\n",
    "  - xception71\n",
    "  - xception41\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "",
   "name": ""
  },
  "language_info": {
   "name": ""
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
